-- MySQL Script generated by MySQL Workbench
-- 07/20/16 20:14:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trabalhofinal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trabalhofinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalhofinal` DEFAULT CHARACTER SET utf8 ;
USE `trabalhofinal` ;

-- -----------------------------------------------------
-- Table `trabalhofinal`.`EmpresaDeAviacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`EmpresaDeAviacao` (
  `idEmpresaDeAviacao` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpresaDeAviacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`FabricanteDaAeronave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`FabricanteDaAeronave` (
  `idFabricanteDaAeronave` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFabricanteDaAeronave`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`ModeloDeAeronave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`ModeloDeAeronave` (
  `idModeloDeAeronave` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `capacidadeDePassageiros` INT NOT NULL,
  `idFabricante` INT NOT NULL,
  `capacidadeDeCombustivel` FLOAT NOT NULL,
  PRIMARY KEY (`idModeloDeAeronave`),
  INDEX `fk_ModeloDeAeronave_FabricanteDaAeronave_idx` (`idFabricante` ASC),
  CONSTRAINT `fk_ModeloDeAeronave_FabricanteDaAeronave`
    FOREIGN KEY (`idFabricante`)
    REFERENCES `trabalhofinal`.`FabricanteDaAeronave` (`idFabricanteDaAeronave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Aeronave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Aeronave` (
  `idAeronave` INT NOT NULL,
  `matricula` VARCHAR(12) NULL,
  `idEmpresaDeAviacao` INT NOT NULL,
  `idModeloDeAeronave` INT NOT NULL,
  `dataDeFabricacao` DATE NULL,
  `tempoDeVoo` TIME NULL,
  PRIMARY KEY (`idAeronave`),
  INDEX `fk_Aeronave_EmpresaDeAviacao1_idx` (`idEmpresaDeAviacao` ASC),
  INDEX `fk_Aeronave_ModeloDeAeronave1_idx` (`idModeloDeAeronave` ASC),
  CONSTRAINT `fk_Aeronave_EmpresaDeAviacao1`
    FOREIGN KEY (`idEmpresaDeAviacao`)
    REFERENCES `trabalhofinal`.`EmpresaDeAviacao` (`idEmpresaDeAviacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aeronave_ModeloDeAeronave1`
    FOREIGN KEY (`idModeloDeAeronave`)
    REFERENCES `trabalhofinal`.`ModeloDeAeronave` (`idModeloDeAeronave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`AutorizacaoOperacional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`AutorizacaoOperacional` (
  `idAutorizacaoOperacional` INT NOT NULL,
  `dataDeEmissao` DATETIME NULL,
  `dataDeVencimento` DATETIME NULL,
  `idEmpresaDeAviacao` INT NOT NULL,
  PRIMARY KEY (`idAutorizacaoOperacional`),
  INDEX `fk_AutorizacaoOperacional_EmpresaDeAviacao1_idx` (`idEmpresaDeAviacao` ASC),
  CONSTRAINT `fk_AutorizacaoOperacional_EmpresaDeAviacao1`
    FOREIGN KEY (`idEmpresaDeAviacao`)
    REFERENCES `trabalhofinal`.`EmpresaDeAviacao` (`idEmpresaDeAviacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Pais` (
  `idPais` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Estado` (
  `idEstado` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idPais` INT NOT NULL,
  PRIMARY KEY (`idEstado`),
  INDEX `fk_Estado_Pais1_idx` (`idPais` ASC),
  CONSTRAINT `fk_Estado_Pais1`
    FOREIGN KEY (`idPais`)
    REFERENCES `trabalhofinal`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Cidade` (
  `idCidade` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idEstado` INT NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX `fk_Cidade_Estado1_idx` (`idEstado` ASC),
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `trabalhofinal`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Aeroporto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Aeroporto` (
  `idAeroporto` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sigla` VARCHAR(10) NOT NULL,
  `idCidade` INT NOT NULL,
  PRIMARY KEY (`idAeroporto`),
  INDEX `fk_Aeroporto_Cidade1_idx` (`idCidade` ASC),
  CONSTRAINT `fk_Aeroporto_Cidade1`
    FOREIGN KEY (`idCidade`)
    REFERENCES `trabalhofinal`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`LinhaAerea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`LinhaAerea` (
  `idLinhaAerea` INT NOT NULL,
  `id_Aeroporto_Origem` INT NOT NULL,
  `id_Aeroporto_Destino` INT NOT NULL,
  `idEmpresaDeAviacao` INT NOT NULL,
  PRIMARY KEY (`idLinhaAerea`),
  INDEX `fk_LinhaAerea_Aeroporto1_idx` (`id_Aeroporto_Origem` ASC),
  INDEX `fk_LinhaAerea_Aeroporto2_idx` (`id_Aeroporto_Destino` ASC),
  INDEX `fk_LinhaAerea_EmpresaDeAviacao1_idx` (`idEmpresaDeAviacao` ASC),
  CONSTRAINT `fk_LinhaAerea_Aeroporto1`
    FOREIGN KEY (`id_Aeroporto_Origem`)
    REFERENCES `trabalhofinal`.`Aeroporto` (`idAeroporto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LinhaAerea_Aeroporto2`
    FOREIGN KEY (`id_Aeroporto_Destino`)
    REFERENCES `trabalhofinal`.`Aeroporto` (`idAeroporto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LinhaAerea_EmpresaDeAviacao1`
    FOREIGN KEY (`idEmpresaDeAviacao`)
    REFERENCES `trabalhofinal`.`EmpresaDeAviacao` (`idEmpresaDeAviacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`StatusDoVoo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`StatusDoVoo` (
  `idStatusDoVoo` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStatusDoVoo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Voo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Voo` (
  `idVoo` INT NOT NULL,
  `idLinhaAerea` INT NOT NULL,
  `data` DATE NOT NULL,
  `horario_saida` TIME NOT NULL,
  `horario_chegada` TIME NOT NULL,
  `idAeronave` INT NOT NULL,
  `milhasConcedidas` INT NULL,
  `idStatusDoVoo` INT NOT NULL,
  PRIMARY KEY (`idVoo`),
  INDEX `fk_Voo_LinhaAerea1_idx` (`idLinhaAerea` ASC),
  INDEX `fk_Voo_Aeronave1_idx` (`idAeronave` ASC),
  INDEX `fk_Voo_StatusDoVoo1_idx` (`idStatusDoVoo` ASC),
  CONSTRAINT `fk_Voo_LinhaAerea1`
    FOREIGN KEY (`idLinhaAerea`)
    REFERENCES `trabalhofinal`.`LinhaAerea` (`idLinhaAerea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voo_Aeronave1`
    FOREIGN KEY (`idAeronave`)
    REFERENCES `trabalhofinal`.`Aeronave` (`idAeronave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voo_StatusDoVoo1`
    FOREIGN KEY (`idStatusDoVoo`)
    REFERENCES `trabalhofinal`.`StatusDoVoo` (`idStatusDoVoo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Passageiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Passageiro` (
  `idPassageiro` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NULL,
  `idade` INT NOT NULL,
  PRIMARY KEY (`idPassageiro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Passagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Passagem` (
  `idPassagem` INT NOT NULL,
  `idVoo` INT NOT NULL,
  `idPassageiro` INT NOT NULL,
  `preco` FLOAT NOT NULL,
  `precoEmMilhas` INT NULL,
  PRIMARY KEY (`idPassagem`),
  INDEX `fk_Passagem_Voo1_idx` (`idVoo` ASC),
  INDEX `fk_Passagem_Passageiro1_idx` (`idPassageiro` ASC),
  CONSTRAINT `fk_Passagem_Voo1`
    FOREIGN KEY (`idVoo`)
    REFERENCES `trabalhofinal`.`Voo` (`idVoo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Passagem_Passageiro1`
    FOREIGN KEY (`idPassageiro`)
    REFERENCES `trabalhofinal`.`Passageiro` (`idPassageiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`CartaoDeEmbarque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`CartaoDeEmbarque` (
  `idPassagem` INT NOT NULL,
  `assento` VARCHAR(5) NULL,
  `codigoDeAutenticacao` VARCHAR(45) NOT NULL,
  INDEX `fk_CartaoDeEmbarque_Passagem1_idx` (`idPassagem` ASC),
  UNIQUE INDEX `Passagem_idPassagem_UNIQUE` (`idPassagem` ASC),
  CONSTRAINT `fk_CartaoDeEmbarque_Passagem1`
    FOREIGN KEY (`idPassagem`)
    REFERENCES `trabalhofinal`.`Passagem` (`idPassagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Funcionario` (
  `idFuncionario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `salario` FLOAT NOT NULL,
  `idEmpresaDeAviacao` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  INDEX `fk_Funcionario_EmpresaDeAviacao1_idx` (`idEmpresaDeAviacao` ASC),
  CONSTRAINT `fk_Funcionario_EmpresaDeAviacao1`
    FOREIGN KEY (`idEmpresaDeAviacao`)
    REFERENCES `trabalhofinal`.`EmpresaDeAviacao` (`idEmpresaDeAviacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Piloto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Piloto` (
  `idFuncionario` INT NOT NULL,
  `CHT` VARCHAR(10) NULL,
  `tempoDeVoo` TIME NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  INDEX `fk_Piloto_Funcionario1_idx` (`idFuncionario` ASC),
  CONSTRAINT `fk_Piloto_Funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `trabalhofinal`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Comissario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Comissario` (
  `idFuncionario` INT NOT NULL,
  `CodLicenca` VARCHAR(45) NULL,
  PRIMARY KEY (`idFuncionario`),
  INDEX `fk_Comissario_Funcionario1_idx` (`idFuncionario` ASC),
  CONSTRAINT `fk_Comissario_Funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `trabalhofinal`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Mecanico` (
  `idFuncionario` INT NOT NULL,
  `CodLicenca` VARCHAR(45) NULL,
  PRIMARY KEY (`idFuncionario`),
  CONSTRAINT `fk_Mecanico_Funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `trabalhofinal`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Administrativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Administrativo` (
  `idFuncionario` INT NOT NULL,
  `cargo` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  CONSTRAINT `fk_Administrativo_Funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `trabalhofinal`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Terceirizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Terceirizado` (
  `idFuncionario` INT NOT NULL,
  `cargo` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  CONSTRAINT `fk_Terceirizado_Funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `trabalhofinal`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Manutencao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Manutencao` (
  `idManutencao` INT NOT NULL,
  `descricao` VARCHAR(250) NOT NULL,
  `data` DATE NOT NULL,
  `idAeronave` INT NOT NULL,
  PRIMARY KEY (`idManutencao`),
  INDEX `fk_Manutencao_Aeronave1_idx` (`idAeronave` ASC),
  CONSTRAINT `fk_Manutencao_Aeronave1`
    FOREIGN KEY (`idAeronave`)
    REFERENCES `trabalhofinal`.`Aeronave` (`idAeronave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`AutorizacaoParaVoar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`AutorizacaoParaVoar` (
  `idAutorizacaoParaVoar` INT NOT NULL,
  `dataDeEmissao` DATE NOT NULL,
  `dataDeVencimento` DATE NOT NULL,
  `idAeronave` INT NOT NULL,
  PRIMARY KEY (`idAutorizacaoParaVoar`),
  INDEX `fk_AutorizacaoDeVoo_Aeronave1_idx` (`idAeronave` ASC),
  CONSTRAINT `fk_AutorizacaoDeVoo_Aeronave1`
    FOREIGN KEY (`idAeronave`)
    REFERENCES `trabalhofinal`.`Aeronave` (`idAeronave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Passaporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Passaporte` (
  `idPassaporte` INT NOT NULL,
  `codigoPassaporte` VARCHAR(15) NOT NULL,
  `idPassageiro` INT NOT NULL,
  `idPais` INT NOT NULL,
  PRIMARY KEY (`idPassaporte`),
  INDEX `fk_Passaporte_Passageiro1_idx` (`idPassageiro` ASC),
  INDEX `fk_Passaporte_Pais1_idx` (`idPais` ASC),
  CONSTRAINT `fk_Passaporte_Passageiro1`
    FOREIGN KEY (`idPassageiro`)
    REFERENCES `trabalhofinal`.`Passageiro` (`idPassageiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Passaporte_Pais1`
    FOREIGN KEY (`idPais`)
    REFERENCES `trabalhofinal`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`MilhasAcumuladas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`MilhasAcumuladas` (
  `idPassageiro` INT NOT NULL,
  `numeroDeMilhas` INT NOT NULL,
  INDEX `fk_MilhasAcumuladas_Passageiro1_idx` (`idPassageiro` ASC),
  PRIMARY KEY (`idPassageiro`),
  CONSTRAINT `fk_MilhasAcumuladas_Passageiro1`
    FOREIGN KEY (`idPassageiro`)
    REFERENCES `trabalhofinal`.`Passageiro` (`idPassageiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalhofinal`.`Piloto_has_Voo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalhofinal`.`Piloto_has_Voo` (
  `idPiloto` INT NOT NULL,
  `idVoo` INT NOT NULL,
  INDEX `fk_Piloto_has_Voo_Piloto1_idx` (`idPiloto` ASC),
  INDEX `fk_Piloto_has_Voo_Voo1_idx` (`idVoo` ASC),
  CONSTRAINT `fk_Piloto_has_Voo_Piloto1`
    FOREIGN KEY (`idPiloto`)
    REFERENCES `trabalhofinal`.`Piloto` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Piloto_has_Voo_Voo1`
    FOREIGN KEY (`idVoo`)
    REFERENCES `trabalhofinal`.`Voo` (`idVoo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
